/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_JavaGUI
#define _Included_JavaGUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaGUI
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaGUI_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JavaGUI
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JavaGUI_calculateMean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
